BlankWebApplication/BlankWebApplication/Models/Domain/Message.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace BlankWebApplication.Models.Domain
{
    public class Message
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int MessageID { get; set; }
        public string Url { get; set; }

        public string TITLE { get; set; }
        public string CONTET { get; set; }
        public string OWNER { get; set; }
        public string TO { get; set; }

    }
}

BlankWebApplication/BlankWebApplication/Models/ErrorViewModel.cs
using System;

namespace BlankWebApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BlankWebApplication/BlankWebApplication/Controllers/EmailController.cs
using BlankWebApplication.DataAccess.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlankWebApplication.Controllers
{
    public class EmailController : Controller
    {
        private readonly IMessagesRepository _messageRepo;
        private readonly IConfiguration _config;
        private readonly IPubSub _pubSubRepo;
        public EmailController(IMessagesRepository messageRepo, IConfiguration config, IPubSub pubSubRepo)
        {
            _messageRepo = messageRepo;
            _config = config;
            _pubSubRepo = pubSubRepo;
        }
        public IActionResult Pull()
        {
            string ser = _pubSubRepo.pullMessage();

            if (ser == string.Empty) return View();

            dynamic mydm = JsonConvert.DeserializeObject(ser);
                string email = mydm.Email;
                string CONTET = mydm.Message.CONTET;
                string MessageID = mydm.Message.MessageID;
                string OWNER = mydm.Message.OWNER;
                string TITLE = mydm.Message.TITLE;
                string TO = mydm.Message.TO;
                string Url = mydm.Message.Url;
            


            return Content("EMAIL SENT "+ email + " CONTET: " + CONTET + " MessageID:" + MessageID + " OWNER: " + OWNER + " TITLE: " + TITLE + " TO: " + TO + " Url: " + Url + " ");
        }
    }
}

BlankWebApplication/BlankWebApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BlankWebApplication.Models;

namespace BlankWebApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BlankWebApplication/BlankWebApplication/Controllers/MessageController.cs
using BlankWebApplication.DataAccess.Interfaces;
using BlankWebApplication.Models.Domain;
using Google.Cloud.Storage.V1;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Google.Cloud.Storage.V1;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;



namespace BlankWebApplication.Controllers


{
    public class MessageController : Controller
    {
        private readonly IMessagesRepository _messageRepo;
        private readonly IConfiguration _config;
        private readonly IPubSub _pubSubRepo;
       public MessageController(IMessagesRepository messageRepo, IConfiguration config, IPubSub pubSubRepo)
        { 
            _messageRepo = messageRepo;
            _config = config;
            _pubSubRepo = pubSubRepo;
        }
        public IActionResult Index()
        {
            var list = _messageRepo.GetMessages();
            return View(list);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(IFormFile logo, Message m)
        {

            try
            {
                string bucketName = _config.GetSection("AppSettings").GetSection("BucketName").Value;
                string uniqueFilename = Guid.NewGuid() + System.IO.Path.GetExtension(logo.FileName);

                //upload a file in the cloud storage
                var storage = StorageClient.Create();

                using (var myStream = logo.OpenReadStream())
                {
                    storage.UploadObject(bucketName, uniqueFilename, null, myStream);
                }

                //add a reference to the file url with the instance of the blog >>> b

                m.Url = $"https://storage.googleapis.com/{bucketName}/{uniqueFilename}";

                _messageRepo.AddMessage(m);

                string eamil_rec = HttpContext.User.Identity.Name;
                _pubSubRepo.PublishMessage(m, eamil_rec, "testing");


                TempData["message"] = $"Message{m.Url}Message could be made";
                return RedirectToAction("Index");
            }catch(Exception ex)
            {
                TempData["error"] = "Message couldn't be made";
                return View(_messageRepo);
            }
         }

        public IActionResult Delete(int id)
        {
            try
            {
                _messageRepo.DeleteMessage(id);
                TempData["message"] = $"Message was deleted successfully";
            }
            catch (Exception
            e)
            {
                TempData["error"] = "Message wasnt deleted successfully";
            }

            return RedirectToAction("Index");
        }
    }
}

BlankWebApplication/BlankWebApplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BlankWebApplication/BlankWebApplication/Views/Message/Create.cshtml
@model BlankWebApplication.Models.Domain.Message

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Message</h4>

@if (TempData["error"] != null)
{
    <div class="alert alert-primary" role="alert">
        @TempData["error"]
    </div>
}
<hr />
<div class="row">
    <div class="col-md-4">
       <form asp-action="Create" enctype="multipart/form-data"  >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MessageID" class="control-label"></label>
                <input asp-for="MessageID" class="form-control" />
                <span asp-validation-for="MessageID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Upload a file</label>
                <input type="file" name="logo" class="form-control" />
           
            </div>
            <div class="form-group">
                <label asp-for="TITLE" class="control-label"></label>
                <input asp-for="TITLE" class="form-control" />
                <span asp-validation-for="TITLE" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CONTET" class="control-label"></label>
                <input asp-for="CONTET" class="form-control" />
                <span asp-validation-for="CONTET" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OWNER" class="control-label"></label>
                <input asp-for="OWNER" class="form-control" />
                <span asp-validation-for="OWNER" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TO" class="control-label"></label>
                <input asp-for="TO" class="form-control" />
                <span asp-validation-for="TO" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BlankWebApplication/BlankWebApplication/Views/Message/Index.cshtml
@model IEnumerable<BlankWebApplication.Models.Domain.Message>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MessageID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Url)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TITLE)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CONTET)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OWNER)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TO)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MessageID)
            </td>
            <td>
                <img src="@item.Url" style="width:230px;height:150px" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TITLE)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CONTET)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OWNER)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TO)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.MessageID  })
            </td>
        </tr>
}
    </tbody>
</table>

BlankWebApplication/BlankWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlankWebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BlankWebApplication</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        
                            <a class="nav-link text-dark" asp-area="" asp-controller="Message" asp-action="Index">index</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Message" asp-action="Create">create</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
             @if (TempData["error"] != null)
            {
                <div class="alert alert-danger" role="alert">
                    @TempData["error"]
                </div>
            }
            @if (TempData["message"] != null)
            {
                <div class="alert alert-primary" role="alert">
                    @TempData["message"]
                </div>
            }

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - BlankWebApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>